export const AVAILABLE_TAGS = [
    { id: 'carne', label: 'Carne', icon: '🥩' },
    { id: 'pescado', label: 'Pescado', icon: '🐟' },
    { id: 'air_fryer', label: 'Air Fryer', icon: '🌬️' },
    { id: 'rapido', label: 'Rápido', icon: '⚡' },
    { id: 'postre', label: 'Postre', icon: '🍰' },
    { id: 'legumbres', label: 'Legumbres', icon: '🫘' },
    { id: 'pasta', label: 'Pasta', icon: '🍝' },
    { id: 'arroz', label: 'Arroz', icon: '🍚' },
    { id: 'sopa', label: 'Sopa', icon: '🍲' },
    { id: 'ensalada', label: 'Ensalada', icon: '🥗' },
    { id: 'guiso', label: 'Guiso', icon: '🥘' },
    { id: 'horno', label: 'Horno', icon: '🔥' },
    { id: 'olla', label: 'Olla', icon: '🥘' },
    { id: 'microondas', label: 'Microondas', icon: '🔌' },
    { id: 'vegano', label: 'Vegano', icon: '🌱' },
    { id: 'verduras', label: 'Verduras', icon: '🥦' },
    { id: 'sin_gluten', label: 'Sin Gluten', icon: '🌾' },
    { id: 'sin_lactosa', label: 'Sin Lactosa', icon: '🥛' },
    { id: 'bajo_en_carbohidratos', label: 'Bajo en Carbohidratos', icon: '📉' },
    { id: 'alto_en_proteinas', label: 'Alto en Proteínas', icon: '💪' },
]